# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BufferWithCenterLine
                                 A QGIS plugin
 A plugin to digitize road lines and automatically generate their buffers in one go
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-07-02
        copyright            : (C) 2026 by Thomas UTM
        email                : dwtom.dprwd@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BufferWithCenterLine class from file BufferWithCenterLine.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .road_digitizer_buffer import BufferWithCenterLine
    return BufferWithCenterLine(iface)
