# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BufferWithCenterLine
                                 A QGIS plugin
 A plugin to digitize road lines and automatically generate their buffers in one go
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Thomas UTM
        email                : dwtom.dprwd@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import (
    QgsSettings,
    QgsProject,
    QgsMapLayer,
    QgsWkbTypes
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMessageBox,
    QDoubleSpinBox,
    QComboBox
)


# Import the code for the dialog
from .road_digitizer_buffer_dialog import BufferWithCenterLineDialog
from .road_digitizer_maptool import RoadDigitizerMapTool
import os.path


class BufferWithCenterLine:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&RoadDigitizz')

        self.toolbar = self.iface.addToolBar("RoadDigitizz")
        self.toolbar.setObjectName("RoadDigitizz")
       
        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        self.line_layer = None
        self.polygon_layer = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BufferWithCenterLine', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(os.path.dirname(__file__), 'icon.png')
        self.add_action(
            icon_path,
            text=self.tr(u'Road Digitizz'),
            callback=self.run,
            parent=self.iface.mainWindow())
        
                # Width SpinBox
        self.widthSpin = QDoubleSpinBox()

        self.widthSpin.setDecimals(1)
        self.widthSpin.setMinimum(1)
        self.widthSpin.setMaximum(100)
        self.widthSpin.setSingleStep(0.5)
        self.widthSpin.setValue(6)
        self.widthSpin.setSuffix(" m")

        self.toolbar.addWidget(self.widthSpin)

        # Cap Style
        self.capCombo = QComboBox()

        self.capCombo.addItem("Flat")
        self.capCombo.addItem("Round")
        self.capCombo.addItem("Square")

        self.capCombo.setToolTip("Buffer Cap Style")

        self.toolbar.addWidget(self.capCombo)
        
        # Join Style
        self.joinCombo = QComboBox()

        self.joinCombo.addItem("Round")
        self.joinCombo.addItem("Miter")
        self.joinCombo.addItem("Bevel")

        self.joinCombo.setToolTip("Buffer Join Style")

        self.toolbar.addWidget(self.joinCombo)

        self.joinCombo.currentTextChanged.connect(self.onJoinStyleChanged)

        self.capCombo.currentTextChanged.connect(self.onCapStyleChanged)

        self.widthSpin.valueChanged.connect(self.onWidthChanged)

        # will be set False in run()
        self.first_start = True

    def onWidthChanged(self, value):

        if hasattr(self, "map_tool") and self.map_tool:

            self.map_tool.setWidth(value)

    def onCapStyleChanged(self, text):

        if hasattr(self, "map_tool") and self.map_tool:
            self.map_tool.setCapStyle(text)

    def onJoinStyleChanged(self, text):

        if hasattr(self, "map_tool") and self.map_tool:
            self.map_tool.setJoinStyle(text)


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&RoadDigitizz'),
                action)
            self.iface.removeToolBarIcon(action)
            
        del self.toolbar

    def populate_layers(self):
        """Populate Line dan Polygon layer ke ComboBox"""

        self.dlg.cmbLineLayer.clear()
        self.dlg.cmbPolygonLayer.clear()

        layers = QgsProject.instance().mapLayers().values()

        for layer in layers:

            if layer.type() != QgsMapLayer.VectorLayer:
                continue

            geom = layer.geometryType()

            if geom == QgsWkbTypes.LineGeometry:
                self.dlg.cmbLineLayer.addItem(layer.name(), layer)

            elif geom == QgsWkbTypes.PolygonGeometry:
                self.dlg.cmbPolygonLayer.addItem(layer.name(), layer)

            # Restore last selected line layer
            if self.line_layer:
                index = self.dlg.cmbLineLayer.findData(self.line_layer)
                if index >= 0:
                    self.dlg.cmbLineLayer.setCurrentIndex(index)

            # Restore last selected polygon layer
            if self.polygon_layer:
                index = self.dlg.cmbPolygonLayer.findData(self.polygon_layer)
                if index >= 0:
                    self.dlg.cmbPolygonLayer.setCurrentIndex(index)
    
    def prepare_digitizing(self):

        self.line_layer = self.dlg.cmbLineLayer.currentData()
        self.polygon_layer = self.dlg.cmbPolygonLayer.currentData()

        line_layer = self.line_layer
        polygon_layer = self.polygon_layer
        width = self.widthSpin.value()

        print("===== RoadDigitizz =====")
        print("Line Layer :", line_layer.name())
        print("Polygon Layer :", polygon_layer.name())
        print("Width :", width)

        # Pastikan layer dalam mode edit
        if not line_layer.isEditable():
            line_layer.startEditing()

        if not polygon_layer.isEditable():
            polygon_layer.startEditing()

        canvas_crs = self.iface.mapCanvas().mapSettings().destinationCrs()

        if canvas_crs.isGeographic():

            QMessageBox.warning(
                self.iface.mainWindow(),
                "RoadDigitizz",
                "Project CRS menggunakan Geographic (Degree).\n\n"
                "Preview buffer mungkin tidak akurat.\n\n"
                "Disarankan menggunakan Projected CRS."
            )
            
        # Aktifkan Map Tool
        self.map_tool = RoadDigitizerMapTool(
            self.iface.mapCanvas(),
            line_layer,
            polygon_layer,
            width
        )
        self.iface.mapCanvas().setMapTool(self.map_tool)

        print("Map Tool Activated")

    def run(self):
        """Run method that performs all the real work"""

        if self.first_start:
            self.first_start = False
            self.dlg = BufferWithCenterLineDialog()

        self.populate_layers()

        result = self.dlg.exec_()

        if result:
            self.prepare_digitizing()