# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BufferWithCenterLine
                                 A QGIS plugin
 A plugin to digitize road lines and automatically generate their buffers in one go
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-02
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Dwi Wahyu Utomo
        email                : dwtom.dprwd@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QLocale, QTranslator, QCoreApplication
from qgis.core import (
    QgsSettings,
    QgsProject,
    QgsMapLayer,
    QgsWkbTypes
)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (
    QAction,
    QMessageBox,
    QDoubleSpinBox,
    QComboBox
)

# Import the code for the dialog
from .road_digitizer_buffer_dialog import BufferWithCenterLineDialog
from .road_digitizer_maptool import RoadDigitizerMapTool
import os.path


class BufferWithCenterLine:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):

        self.iface = iface
        self.plugin_dir = os.path.dirname(__file__)

        locale = QgsSettings().value('locale/userLocale', QLocale().name())[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            '{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        self.actions = []
        self.toolbar_widgets = []

        self.menu = self.tr(u'&RoadDigitizz')

        self.toolbar = self.iface.addToolBar("RoadDigitizz")
        self.toolbar.setObjectName("RoadDigitizz")

        self.first_start = None
        self.line_layer = None
        self.polygon_layer = None
        self.last_line_layer_id = None
        self.last_polygon_layer_id = None

    def tr(self, message):

        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BufferWithCenterLine', message)

    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None,
    ):

        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)
        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = os.path.join(
            os.path.dirname(__file__),
            "toolbar_icon.png"
        )

        self.add_action(
            icon_path,
            text=self.tr(u'Road Digitizz'),
            callback=self.run,
            parent=self.iface.mainWindow())
        # Width SpinBox
        self.widthSpin = QDoubleSpinBox()
        self.widthSpin.setDecimals(2)
        self.widthSpin.setMinimum(1)
        self.widthSpin.setMaximum(100)
        self.widthSpin.setSingleStep(0.5)
        self.widthSpin.setValue(6)
        self.widthSpin.setSuffix(" m")

        action = self.toolbar.addWidget(self.widthSpin)
        self.toolbar_widgets.append(action)

        # Cap Style
        self.capCombo = QComboBox()
        self.capCombo.addItem("Flat")
        self.capCombo.addItem("Round")
        self.capCombo.addItem("Square")
        self.capCombo.setToolTip("Buffer Cap Style")

        action = self.toolbar.addWidget(self.capCombo)
        self.toolbar_widgets.append(action)

        # Join Style
        self.joinCombo = QComboBox()
        self.joinCombo.addItem("Round")
        self.joinCombo.addItem("Miter")
        self.joinCombo.addItem("Bevel")
        self.joinCombo.setToolTip("Buffer Join Style")

        action = self.toolbar.addWidget(self.joinCombo)
        self.toolbar_widgets.append(action)

        self.joinCombo.currentTextChanged.connect(self.onJoinStyleChanged)
        self.capCombo.currentTextChanged.connect(self.onCapStyleChanged)
        self.widthSpin.valueChanged.connect(self.onWidthChanged)

        # will be set False in run()
        self.first_start = True

    def onWidthChanged(self, value):

        if hasattr(self, "map_tool") and self.map_tool:
            self.map_tool.setWidth(value)

    def onCapStyleChanged(self, text):

        if hasattr(self, "map_tool") and self.map_tool:
            self.map_tool.setCapStyle(text)

    def onJoinStyleChanged(self, text):

        if hasattr(self, "map_tool") and self.map_tool:
            self.map_tool.setJoinStyle(text)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # 1. Cleanup map tool
        if getattr(self, "map_tool", None):
            try:
                self.map_tool.cleanup()
            except AttributeError:
                pass

            self.iface.mapCanvas().unsetMapTool(
                self.map_tool
            )

            self.map_tool = None

        # 2. Remove plugin actions
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&RoadDigitizz'),
                action
            )

            self.iface.removeToolBarIcon(action)

        self.actions.clear()

        # 3. Remove custom toolbar widgets
        for widget_action in self.toolbar_widgets:
            self.toolbar.removeAction(widget_action)

        self.toolbar_widgets.clear()

        # 4. Remove toolbar
        self.iface.mainWindow().removeToolBar(
            self.toolbar
        )

        self.toolbar.setParent(None)
        self.toolbar.deleteLater()
        self.toolbar = None

    def populate_layers(self):
        """Populate Line dan Polygon layer ke ComboBox"""

        self.dlg.cmbLineLayer.clear()
        self.dlg.cmbPolygonLayer.clear()

        self.dlg.cmbLineLayer.addItem(
            "-- Select Centerline Layer --",
            None
        )
        self.dlg.cmbPolygonLayer.addItem(
            "-- Select Polygon Layer --",
            None
        )

        layers = QgsProject.instance().mapLayers().values()

        for layer in layers:
            if layer.type() != QgsMapLayer.LayerType.VectorLayer:
                continue

            geom = layer.geometryType()
            if geom == QgsWkbTypes.GeometryType.LineGeometry:
                self.dlg.cmbLineLayer.addItem(layer.name(), layer)
            elif geom == QgsWkbTypes.GeometryType.PolygonGeometry:
                self.dlg.cmbPolygonLayer.addItem(layer.name(), layer)

        # Restore last selected line layer
        found = False

        if self.last_line_layer_id:

            for i in range(self.dlg.cmbLineLayer.count()):
                layer = self.dlg.cmbLineLayer.itemData(i)
                if layer and layer.id() == self.last_line_layer_id:
                    self.dlg.cmbLineLayer.setCurrentIndex(i)
                    found = True
                    break
            if not found:
                self.last_line_layer_id = None

        # Restore last selected polygon layer
        found = False

        if self.last_polygon_layer_id:
            for i in range(self.dlg.cmbPolygonLayer.count()):
                layer = self.dlg.cmbPolygonLayer.itemData(i)
                if layer and layer.id() == self.last_polygon_layer_id:
                    self.dlg.cmbPolygonLayer.setCurrentIndex(i)
                    found = True
                    break
            if not found:
                self.last_polygon_layer_id = None

    def prepare_digitizing(self):

        self.line_layer = self.dlg.cmbLineLayer.currentData()
        self.polygon_layer = self.dlg.cmbPolygonLayer.currentData()

        if self.line_layer is None:
            QMessageBox.warning(
                self.dlg,
                "RoadDigitizz",
                "Please select a centerline layer."
            )
            return

        if self.polygon_layer is None:
            QMessageBox.warning(
                self.dlg,
                "RoadDigitizz",
                "Please select a polygon layer."
            )
            return

        self.last_line_layer_id = self.line_layer.id()
        self.last_polygon_layer_id = self.polygon_layer.id()

        line_layer = self.line_layer
        polygon_layer = self.polygon_layer
        width = self.widthSpin.value()

        if not line_layer.isEditable():
            line_layer.startEditing()

        if not polygon_layer.isEditable():
            polygon_layer.startEditing()

        if getattr(self, "map_tool", None):
            if self.iface.mapCanvas().mapTool() == self.map_tool:
                self.map_tool.cancelDigitizing()
                self.iface.mapCanvas().unsetMapTool(self.map_tool)

        self.map_tool = RoadDigitizerMapTool(
            self.iface.mapCanvas(),
            line_layer,
            polygon_layer,
            width
        )

        self.map_tool.setWidth(
            self.widthSpin.value()
        )
        self.map_tool.setCapStyle(
            self.capCombo.currentText()
        )
        self.map_tool.setJoinStyle(
            self.joinCombo.currentText()
        )

        self.iface.mapCanvas().setMapTool(self.map_tool)

    def run(self):
        """Run method that performs all the real work"""

        if self.first_start:
            self.first_start = False
            self.dlg = BufferWithCenterLineDialog()

        self.populate_layers()
        result = self.dlg.exec()

        if result:
            self.prepare_digitizing()
